# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'option_window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Opciones(object):
    def setupUi(self, Opciones):
        Opciones.setObjectName("Opciones")
        Opciones.resize(775, 833)
        Opciones.setModal(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Opciones)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QtWidgets.QSplitter(Opciones)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.listWidgetDevices = QtWidgets.QListWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidgetDevices.sizePolicy().hasHeightForWidth())
        self.listWidgetDevices.setSizePolicy(sizePolicy)
        self.listWidgetDevices.setMinimumSize(QtCore.QSize(150, 0))
        self.listWidgetDevices.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidgetDevices.setObjectName("listWidgetDevices")
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDevices.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDevices.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDevices.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidgetDevices.addItem(item)
        self.tabStackWidget = QtWidgets.QStackedWidget(self.splitter)
        self.tabStackWidget.setEnabled(True)
        self.tabStackWidget.setAutoFillBackground(False)
        self.tabStackWidget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.tabStackWidget.setObjectName("tabStackWidget")
        self.centralServerWidget = QtWidgets.QWidget()
        self.centralServerWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralServerWidget.sizePolicy().hasHeightForWidth())
        self.centralServerWidget.setSizePolicy(sizePolicy)
        self.centralServerWidget.setObjectName("centralServerWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralServerWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_server_1 = QtWidgets.QGroupBox(self.centralServerWidget)
        self.groupBox_server_1.setEnabled(True)
        self.groupBox_server_1.setObjectName("groupBox_server_1")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.groupBox_server_1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout()
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.gridLayout_12 = QtWidgets.QGridLayout()
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox_server_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout_12.addWidget(self.label_8, 0, 0, 1, 1)
        self.lineEdit_server_1 = QtWidgets.QLineEdit(self.groupBox_server_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_server_1.sizePolicy().hasHeightForWidth())
        self.lineEdit_server_1.setSizePolicy(sizePolicy)
        self.lineEdit_server_1.setText("")
        self.lineEdit_server_1.setPlaceholderText("")
        self.lineEdit_server_1.setObjectName("lineEdit_server_1")
        self.gridLayout_12.addWidget(self.lineEdit_server_1, 0, 1, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.groupBox_server_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        self.label_34.setObjectName("label_34")
        self.gridLayout_12.addWidget(self.label_34, 1, 0, 1, 1)
        self.lineEdit_server_9 = QtWidgets.QLineEdit(self.groupBox_server_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_server_9.sizePolicy().hasHeightForWidth())
        self.lineEdit_server_9.setSizePolicy(sizePolicy)
        self.lineEdit_server_9.setText("")
        self.lineEdit_server_9.setObjectName("lineEdit_server_9")
        self.gridLayout_12.addWidget(self.lineEdit_server_9, 1, 1, 1, 1)
        self.verticalLayout_23.addLayout(self.gridLayout_12)
        self.groupBox = QtWidgets.QGroupBox(self.groupBox_server_1)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_server_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_server_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_server_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_server_2.setSizePolicy(sizePolicy)
        self.lineEdit_server_2.setText("")
        self.lineEdit_server_2.setObjectName("lineEdit_server_2")
        self.gridLayout.addWidget(self.lineEdit_server_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_server_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_server_3.setText("")
        self.lineEdit_server_3.setObjectName("lineEdit_server_3")
        self.gridLayout.addWidget(self.lineEdit_server_3, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_server = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_server.setMinimum(1000)
        self.spinBox_server.setMaximum(10000)
        self.spinBox_server.setSingleStep(10)
        self.spinBox_server.setObjectName("spinBox_server")
        self.gridLayout.addWidget(self.spinBox_server, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout_23.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox_server_1)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 0, 1, 1)
        self.lineEdit_server_4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_server_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_server_4.sizePolicy().hasHeightForWidth())
        self.lineEdit_server_4.setSizePolicy(sizePolicy)
        self.lineEdit_server_4.setText("")
        self.lineEdit_server_4.setObjectName("lineEdit_server_4")
        self.gridLayout_11.addWidget(self.lineEdit_server_4, 0, 1, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_11.addWidget(self.label_32, 1, 0, 1, 1)
        self.lineEdit_server_8 = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_server_8.setText("")
        self.lineEdit_server_8.setObjectName("lineEdit_server_8")
        self.gridLayout_11.addWidget(self.lineEdit_server_8, 1, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_11.addWidget(self.label_33, 2, 0, 1, 1)
        self.spinBox_server_3 = QtWidgets.QSpinBox(self.groupBox_2)
        self.spinBox_server_3.setMinimum(1000)
        self.spinBox_server_3.setMaximum(10000)
        self.spinBox_server_3.setSingleStep(10)
        self.spinBox_server_3.setObjectName("spinBox_server_3")
        self.gridLayout_11.addWidget(self.spinBox_server_3, 2, 1, 1, 1)
        self.verticalLayout_22.addLayout(self.gridLayout_11)
        self.verticalLayout_23.addWidget(self.groupBox_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_server = QtWidgets.QPushButton(self.groupBox_server_1)
        self.pushButton_server.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_server.sizePolicy().hasHeightForWidth())
        self.pushButton_server.setSizePolicy(sizePolicy)
        self.pushButton_server.setObjectName("pushButton_server")
        self.horizontalLayout.addWidget(self.pushButton_server)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_23.addLayout(self.horizontalLayout)
        self.verticalLayout_24.addLayout(self.verticalLayout_23)
        self.verticalLayout.addWidget(self.groupBox_server_1)
        self.groupBox_server_2 = QtWidgets.QGroupBox(self.centralServerWidget)
        self.groupBox_server_2.setEnabled(True)
        self.groupBox_server_2.setObjectName("groupBox_server_2")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.groupBox_server_2)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout()
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.comboBox_server = QtWidgets.QComboBox(self.groupBox_server_2)
        self.comboBox_server.setObjectName("comboBox_server")
        self.comboBox_server.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_server)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_server_2)
        self.label_6.setEnabled(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.lineEdit_server_5 = QtWidgets.QLineEdit(self.groupBox_server_2)
        self.lineEdit_server_5.setEnabled(False)
        self.lineEdit_server_5.setText("")
        self.lineEdit_server_5.setObjectName("lineEdit_server_5")
        self.gridLayout_2.addWidget(self.lineEdit_server_5, 0, 1, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.groupBox_server_2)
        self.label_35.setEnabled(True)
        self.label_35.setObjectName("label_35")
        self.gridLayout_2.addWidget(self.label_35, 1, 0, 1, 1)
        self.lineEdit_server_10 = QtWidgets.QLineEdit(self.groupBox_server_2)
        self.lineEdit_server_10.setEnabled(False)
        self.lineEdit_server_10.setText("")
        self.lineEdit_server_10.setObjectName("lineEdit_server_10")
        self.gridLayout_2.addWidget(self.lineEdit_server_10, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_server_2)
        self.label.setEnabled(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 2, 0, 1, 1)
        self.lineEdit_server_6 = QtWidgets.QLineEdit(self.groupBox_server_2)
        self.lineEdit_server_6.setEnabled(False)
        self.lineEdit_server_6.setText("")
        self.lineEdit_server_6.setObjectName("lineEdit_server_6")
        self.gridLayout_2.addWidget(self.lineEdit_server_6, 2, 1, 1, 1)
        self.lineEdit_server_11 = QtWidgets.QLineEdit(self.groupBox_server_2)
        self.lineEdit_server_11.setEnabled(False)
        self.lineEdit_server_11.setText("")
        self.lineEdit_server_11.setObjectName("lineEdit_server_11")
        self.gridLayout_2.addWidget(self.lineEdit_server_11, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_server_2)
        self.label_2.setEnabled(True)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.lineEdit_server_7 = QtWidgets.QLineEdit(self.groupBox_server_2)
        self.lineEdit_server_7.setEnabled(False)
        self.lineEdit_server_7.setText("")
        self.lineEdit_server_7.setObjectName("lineEdit_server_7")
        self.gridLayout_2.addWidget(self.lineEdit_server_7, 3, 1, 1, 1)
        self.lineEdit_server_12 = QtWidgets.QLineEdit(self.groupBox_server_2)
        self.lineEdit_server_12.setEnabled(False)
        self.lineEdit_server_12.setText("")
        self.lineEdit_server_12.setObjectName("lineEdit_server_12")
        self.gridLayout_2.addWidget(self.lineEdit_server_12, 3, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_server_2)
        self.label_9.setEnabled(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 4, 0, 1, 1)
        self.spinBox_server_2 = QtWidgets.QSpinBox(self.groupBox_server_2)
        self.spinBox_server_2.setEnabled(False)
        self.spinBox_server_2.setMaximum(10000)
        self.spinBox_server_2.setSingleStep(10)
        self.spinBox_server_2.setObjectName("spinBox_server_2")
        self.gridLayout_2.addWidget(self.spinBox_server_2, 4, 1, 1, 1)
        self.spinBox_server_4 = QtWidgets.QSpinBox(self.groupBox_server_2)
        self.spinBox_server_4.setEnabled(False)
        self.spinBox_server_4.setMaximum(10000)
        self.spinBox_server_4.setSingleStep(10)
        self.spinBox_server_4.setObjectName("spinBox_server_4")
        self.gridLayout_2.addWidget(self.spinBox_server_4, 4, 2, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_2)
        self.verticalLayout_25.addLayout(self.verticalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_server_5 = QtWidgets.QPushButton(self.groupBox_server_2)
        self.pushButton_server_5.setEnabled(False)
        self.pushButton_server_5.setObjectName("pushButton_server_5")
        self.horizontalLayout_3.addWidget(self.pushButton_server_5)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_25.addLayout(self.horizontalLayout_3)
        self.verticalLayout_27.addLayout(self.verticalLayout_25)
        self.verticalLayout.addWidget(self.groupBox_server_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralServerWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.comboBox_server_2 = QtWidgets.QComboBox(self.groupBox_3)
        self.comboBox_server_2.setObjectName("comboBox_server_2")
        self.comboBox_server_2.addItem("")
        self.verticalLayout_7.addWidget(self.comboBox_server_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_server_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_server_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_server_2.sizePolicy().hasHeightForWidth())
        self.pushButton_server_2.setSizePolicy(sizePolicy)
        self.pushButton_server_2.setObjectName("pushButton_server_2")
        self.horizontalLayout_2.addWidget(self.pushButton_server_2)
        self.pushButton_server_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_server_3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_server_3.sizePolicy().hasHeightForWidth())
        self.pushButton_server_3.setSizePolicy(sizePolicy)
        self.pushButton_server_3.setObjectName("pushButton_server_3")
        self.horizontalLayout_2.addWidget(self.pushButton_server_3)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.verticalLayout_26.addLayout(self.verticalLayout_7)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.pushButton_server_4 = QtWidgets.QPushButton(self.centralServerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_server_4.sizePolicy().hasHeightForWidth())
        self.pushButton_server_4.setSizePolicy(sizePolicy)
        self.pushButton_server_4.setObjectName("pushButton_server_4")
        self.verticalLayout.addWidget(self.pushButton_server_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.tabStackWidget.addWidget(self.centralServerWidget)
        self.grabadorWidget = QtWidgets.QWidget()
        self.grabadorWidget.setObjectName("grabadorWidget")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.grabadorWidget)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.groupBox_grabador_1 = QtWidgets.QGroupBox(self.grabadorWidget)
        self.groupBox_grabador_1.setObjectName("groupBox_grabador_1")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_grabador_1)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.comboBox_grabador = QtWidgets.QComboBox(self.groupBox_grabador_1)
        self.comboBox_grabador.setObjectName("comboBox_grabador")
        self.comboBox_grabador.addItem("")
        self.verticalLayout_14.addWidget(self.comboBox_grabador)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.groupBox_grabador_2 = QtWidgets.QGroupBox(self.groupBox_grabador_1)
        self.groupBox_grabador_2.setEnabled(True)
        self.groupBox_grabador_2.setObjectName("groupBox_grabador_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.groupBox_grabador_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_13 = QtWidgets.QLabel(self.groupBox_grabador_2)
        self.label_13.setEnabled(True)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 1, 0, 1, 1)
        self.lineEdit_grabador_3 = QtWidgets.QLineEdit(self.groupBox_grabador_2)
        self.lineEdit_grabador_3.setEnabled(False)
        self.lineEdit_grabador_3.setText("")
        self.lineEdit_grabador_3.setObjectName("lineEdit_grabador_3")
        self.gridLayout_3.addWidget(self.lineEdit_grabador_3, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox_grabador_2)
        self.label_10.setEnabled(True)
        self.label_10.setObjectName("label_10")
        self.gridLayout_3.addWidget(self.label_10, 0, 0, 1, 1)
        self.lineEdit_grabador_1 = QtWidgets.QLineEdit(self.groupBox_grabador_2)
        self.lineEdit_grabador_1.setEnabled(False)
        self.lineEdit_grabador_1.setObjectName("lineEdit_grabador_1")
        self.gridLayout_3.addWidget(self.lineEdit_grabador_1, 0, 1, 1, 1)
        self.doubleSpinBox_grabador_1 = QtWidgets.QDoubleSpinBox(self.groupBox_grabador_2)
        self.doubleSpinBox_grabador_1.setEnabled(False)
        self.doubleSpinBox_grabador_1.setSingleStep(0.1)
        self.doubleSpinBox_grabador_1.setObjectName("doubleSpinBox_grabador_1")
        self.gridLayout_3.addWidget(self.doubleSpinBox_grabador_1, 1, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_grabador_2)
        self.label_11.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 3, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_grabador_2)
        self.label_12.setEnabled(True)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_grabador_2 = QtWidgets.QLineEdit(self.groupBox_grabador_2)
        self.lineEdit_grabador_2.setEnabled(False)
        self.lineEdit_grabador_2.setObjectName("lineEdit_grabador_2")
        self.gridLayout_3.addWidget(self.lineEdit_grabador_2, 2, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_3)
        self.verticalLayout_13.addWidget(self.groupBox_grabador_2)
        self.groupBox_grabador_3 = QtWidgets.QGroupBox(self.groupBox_grabador_1)
        self.groupBox_grabador_3.setEnabled(True)
        self.groupBox_grabador_3.setObjectName("groupBox_grabador_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.groupBox_grabador_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_31 = QtWidgets.QLabel(self.groupBox_grabador_3)
        self.label_31.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_31.sizePolicy().hasHeightForWidth())
        self.label_31.setSizePolicy(sizePolicy)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 0, 0, 1, 1)
        self.lineEdit_grabador_4 = QtWidgets.QLineEdit(self.groupBox_grabador_3)
        self.lineEdit_grabador_4.setEnabled(False)
        self.lineEdit_grabador_4.setText("")
        self.lineEdit_grabador_4.setObjectName("lineEdit_grabador_4")
        self.gridLayout_4.addWidget(self.lineEdit_grabador_4, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_grabador_3)
        self.label_14.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.gridLayout_4.addWidget(self.label_14, 1, 0, 1, 1)
        self.spinBox_grabador_2 = QtWidgets.QSpinBox(self.groupBox_grabador_3)
        self.spinBox_grabador_2.setEnabled(False)
        self.spinBox_grabador_2.setMaximum(10)
        self.spinBox_grabador_2.setObjectName("spinBox_grabador_2")
        self.gridLayout_4.addWidget(self.spinBox_grabador_2, 1, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_grabador_3)
        self.label_15.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.spinBox_grabador_3 = QtWidgets.QSpinBox(self.groupBox_grabador_3)
        self.spinBox_grabador_3.setEnabled(False)
        self.spinBox_grabador_3.setMaximum(10)
        self.spinBox_grabador_3.setProperty("value", 1)
        self.spinBox_grabador_3.setObjectName("spinBox_grabador_3")
        self.gridLayout_4.addWidget(self.spinBox_grabador_3, 2, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_4)
        self.verticalLayout_13.addWidget(self.groupBox_grabador_3)
        self.groupBox_grabador_4 = QtWidgets.QGroupBox(self.groupBox_grabador_1)
        self.groupBox_grabador_4.setEnabled(True)
        self.groupBox_grabador_4.setObjectName("groupBox_grabador_4")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_grabador_4)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_16 = QtWidgets.QLabel(self.groupBox_grabador_4)
        self.label_16.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 0, 1, 1)
        self.lineEdit_grabador_5 = QtWidgets.QLineEdit(self.groupBox_grabador_4)
        self.lineEdit_grabador_5.setEnabled(False)
        self.lineEdit_grabador_5.setText("")
        self.lineEdit_grabador_5.setObjectName("lineEdit_grabador_5")
        self.gridLayout_5.addWidget(self.lineEdit_grabador_5, 0, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_grabador_4)
        self.label_17.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.lineEdit_grabador_6 = QtWidgets.QLineEdit(self.groupBox_grabador_4)
        self.lineEdit_grabador_6.setEnabled(False)
        self.lineEdit_grabador_6.setText("")
        self.lineEdit_grabador_6.setObjectName("lineEdit_grabador_6")
        self.gridLayout_5.addWidget(self.lineEdit_grabador_6, 1, 1, 1, 1)
        self.verticalLayout_12.addLayout(self.gridLayout_5)
        self.verticalLayout_13.addWidget(self.groupBox_grabador_4)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_grabador = QtWidgets.QPushButton(self.groupBox_grabador_1)
        self.pushButton_grabador.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_grabador.sizePolicy().hasHeightForWidth())
        self.pushButton_grabador.setSizePolicy(sizePolicy)
        self.pushButton_grabador.setObjectName("pushButton_grabador")
        self.horizontalLayout_6.addWidget(self.pushButton_grabador)
        self.pushButton_grabador_2 = QtWidgets.QPushButton(self.groupBox_grabador_1)
        self.pushButton_grabador_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_grabador_2.sizePolicy().hasHeightForWidth())
        self.pushButton_grabador_2.setSizePolicy(sizePolicy)
        self.pushButton_grabador_2.setObjectName("pushButton_grabador_2")
        self.horizontalLayout_6.addWidget(self.pushButton_grabador_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.verticalLayout_10.addWidget(self.groupBox_grabador_1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem5)
        self.tabStackWidget.addWidget(self.grabadorWidget)
        self.detectorWidget = QtWidgets.QWidget()
        self.detectorWidget.setObjectName("detectorWidget")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.detectorWidget)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.groupBox_deco_1 = QtWidgets.QGroupBox(self.detectorWidget)
        self.groupBox_deco_1.setObjectName("groupBox_deco_1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.groupBox_deco_1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.comboBox_deco = QtWidgets.QComboBox(self.groupBox_deco_1)
        self.comboBox_deco.setObjectName("comboBox_deco")
        self.comboBox_deco.addItem("")
        self.verticalLayout_16.addWidget(self.comboBox_deco)
        self.groupBox_deco_2 = QtWidgets.QGroupBox(self.groupBox_deco_1)
        self.groupBox_deco_2.setEnabled(True)
        self.groupBox_deco_2.setObjectName("groupBox_deco_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_deco_2)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_deco_2)
        self.label_21.setEnabled(True)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 1)
        self.lineEdit_deco_1 = QtWidgets.QLineEdit(self.groupBox_deco_2)
        self.lineEdit_deco_1.setEnabled(False)
        self.lineEdit_deco_1.setObjectName("lineEdit_deco_1")
        self.gridLayout_6.addWidget(self.lineEdit_deco_1, 0, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_deco_2)
        self.label_19.setEnabled(True)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 1, 0, 1, 1)
        self.lineEdit_deco_2 = QtWidgets.QLineEdit(self.groupBox_deco_2)
        self.lineEdit_deco_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_deco_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_deco_2.setSizePolicy(sizePolicy)
        self.lineEdit_deco_2.setText("")
        self.lineEdit_deco_2.setObjectName("lineEdit_deco_2")
        self.gridLayout_6.addWidget(self.lineEdit_deco_2, 1, 1, 1, 1)
        self.verticalLayout_15.addLayout(self.gridLayout_6)
        self.verticalLayout_16.addWidget(self.groupBox_deco_2)
        self.groupBox_deco_3 = QtWidgets.QGroupBox(self.groupBox_deco_1)
        self.groupBox_deco_3.setEnabled(True)
        self.groupBox_deco_3.setObjectName("groupBox_deco_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_deco_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_22 = QtWidgets.QLabel(self.groupBox_deco_3)
        self.label_22.setEnabled(True)
        self.label_22.setObjectName("label_22")
        self.gridLayout_7.addWidget(self.label_22, 0, 0, 1, 1)
        self.lineEdit_deco_3 = QtWidgets.QLineEdit(self.groupBox_deco_3)
        self.lineEdit_deco_3.setEnabled(False)
        self.lineEdit_deco_3.setObjectName("lineEdit_deco_3")
        self.gridLayout_7.addWidget(self.lineEdit_deco_3, 0, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_deco_3)
        self.label_20.setEnabled(True)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 1, 0, 1, 1)
        self.doubleSpinBox_deco = QtWidgets.QDoubleSpinBox(self.groupBox_deco_3)
        self.doubleSpinBox_deco.setEnabled(False)
        self.doubleSpinBox_deco.setSuffix("")
        self.doubleSpinBox_deco.setMaximum(100.0)
        self.doubleSpinBox_deco.setSingleStep(0.5)
        self.doubleSpinBox_deco.setObjectName("doubleSpinBox_deco")
        self.gridLayout_7.addWidget(self.doubleSpinBox_deco, 1, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_7)
        self.verticalLayout_16.addWidget(self.groupBox_deco_3)
        self.groupBox_deco_4 = QtWidgets.QGroupBox(self.groupBox_deco_1)
        self.groupBox_deco_4.setEnabled(True)
        self.groupBox_deco_4.setObjectName("groupBox_deco_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_deco_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pushButton_deco_2 = QtWidgets.QPushButton(self.groupBox_deco_4)
        self.pushButton_deco_2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deco_2.sizePolicy().hasHeightForWidth())
        self.pushButton_deco_2.setSizePolicy(sizePolicy)
        self.pushButton_deco_2.setObjectName("pushButton_deco_2")
        self.verticalLayout_5.addWidget(self.pushButton_deco_2)
        self.verticalLayout_16.addWidget(self.groupBox_deco_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_deco_1 = QtWidgets.QPushButton(self.groupBox_deco_1)
        self.pushButton_deco_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_deco_1.sizePolicy().hasHeightForWidth())
        self.pushButton_deco_1.setSizePolicy(sizePolicy)
        self.pushButton_deco_1.setObjectName("pushButton_deco_1")
        self.horizontalLayout_5.addWidget(self.pushButton_deco_1)
        self.pushButton_deco_3 = QtWidgets.QPushButton(self.groupBox_deco_1)
        self.pushButton_deco_3.setEnabled(False)
        self.pushButton_deco_3.setObjectName("pushButton_deco_3")
        self.horizontalLayout_5.addWidget(self.pushButton_deco_3)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_16.addLayout(self.horizontalLayout_5)
        self.verticalLayout_21.addWidget(self.groupBox_deco_1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem7)
        self.tabStackWidget.addWidget(self.detectorWidget)
        self.desktopAppWidget = QtWidgets.QWidget()
        self.desktopAppWidget.setObjectName("desktopAppWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.desktopAppWidget)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_app_1 = QtWidgets.QGroupBox(self.desktopAppWidget)
        self.groupBox_app_1.setObjectName("groupBox_app_1")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.groupBox_app_1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_23 = QtWidgets.QLabel(self.groupBox_app_1)
        self.label_23.setEnabled(True)
        self.label_23.setObjectName("label_23")
        self.gridLayout_9.addWidget(self.label_23, 0, 0, 1, 1)
        self.pushButton_app_1 = QtWidgets.QPushButton(self.groupBox_app_1)
        self.pushButton_app_1.setText("")
        self.pushButton_app_1.setObjectName("pushButton_app_1")
        self.gridLayout_9.addWidget(self.pushButton_app_1, 0, 2, 1, 1)
        self.lineEdit_app_1 = QtWidgets.QLineEdit(self.groupBox_app_1)
        self.lineEdit_app_1.setEnabled(True)
        self.lineEdit_app_1.setText("")
        self.lineEdit_app_1.setObjectName("lineEdit_app_1")
        self.gridLayout_9.addWidget(self.lineEdit_app_1, 0, 1, 1, 1)
        self.verticalLayout_19.addLayout(self.gridLayout_9)
        self.verticalLayout_11.addWidget(self.groupBox_app_1)
        self.groupBox_app_2 = QtWidgets.QGroupBox(self.desktopAppWidget)
        self.groupBox_app_2.setObjectName("groupBox_app_2")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.groupBox_app_2)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.comboBox_app = QtWidgets.QComboBox(self.groupBox_app_2)
        self.comboBox_app.setObjectName("comboBox_app")
        self.comboBox_app.addItem("")
        self.verticalLayout_17.addWidget(self.comboBox_app)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.checkBox_app_1 = QtWidgets.QCheckBox(self.groupBox_app_2)
        self.checkBox_app_1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_app_1.sizePolicy().hasHeightForWidth())
        self.checkBox_app_1.setSizePolicy(sizePolicy)
        self.checkBox_app_1.setText("")
        self.checkBox_app_1.setObjectName("checkBox_app_1")
        self.gridLayout_8.addWidget(self.checkBox_app_1, 0, 0, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.groupBox_app_2)
        self.label_24.setEnabled(True)
        self.label_24.setObjectName("label_24")
        self.gridLayout_8.addWidget(self.label_24, 0, 1, 1, 1)
        self.checkBox_app_2 = QtWidgets.QCheckBox(self.groupBox_app_2)
        self.checkBox_app_2.setEnabled(False)
        self.checkBox_app_2.setText("")
        self.checkBox_app_2.setObjectName("checkBox_app_2")
        self.gridLayout_8.addWidget(self.checkBox_app_2, 1, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.groupBox_app_2)
        self.label_25.setEnabled(True)
        self.label_25.setObjectName("label_25")
        self.gridLayout_8.addWidget(self.label_25, 1, 1, 1, 1)
        self.checkBox_app_3 = QtWidgets.QCheckBox(self.groupBox_app_2)
        self.checkBox_app_3.setEnabled(False)
        self.checkBox_app_3.setText("")
        self.checkBox_app_3.setObjectName("checkBox_app_3")
        self.gridLayout_8.addWidget(self.checkBox_app_3, 2, 0, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.groupBox_app_2)
        self.label_27.setEnabled(True)
        self.label_27.setObjectName("label_27")
        self.gridLayout_8.addWidget(self.label_27, 2, 1, 1, 1)
        self.checkBox_app_4 = QtWidgets.QCheckBox(self.groupBox_app_2)
        self.checkBox_app_4.setEnabled(False)
        self.checkBox_app_4.setText("")
        self.checkBox_app_4.setObjectName("checkBox_app_4")
        self.gridLayout_8.addWidget(self.checkBox_app_4, 3, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.groupBox_app_2)
        self.label_26.setEnabled(True)
        self.label_26.setObjectName("label_26")
        self.gridLayout_8.addWidget(self.label_26, 3, 1, 1, 1)
        self.horizontalLayout_4.addLayout(self.gridLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.verticalLayout_17.addLayout(self.horizontalLayout_4)
        self.verticalLayout_11.addWidget(self.groupBox_app_2)
        self.groupBox_app_3 = QtWidgets.QGroupBox(self.desktopAppWidget)
        self.groupBox_app_3.setObjectName("groupBox_app_3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.groupBox_app_3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.gridLayout_10 = QtWidgets.QGridLayout()
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_28 = QtWidgets.QLabel(self.groupBox_app_3)
        self.label_28.setEnabled(True)
        self.label_28.setObjectName("label_28")
        self.gridLayout_10.addWidget(self.label_28, 0, 0, 1, 1)
        self.lineEdit_app_2 = QtWidgets.QLineEdit(self.groupBox_app_3)
        self.lineEdit_app_2.setEnabled(True)
        self.lineEdit_app_2.setText("")
        self.lineEdit_app_2.setObjectName("lineEdit_app_2")
        self.gridLayout_10.addWidget(self.lineEdit_app_2, 0, 1, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.groupBox_app_3)
        self.label_29.setEnabled(True)
        self.label_29.setObjectName("label_29")
        self.gridLayout_10.addWidget(self.label_29, 1, 0, 1, 1)
        self.spinBox_app = QtWidgets.QSpinBox(self.groupBox_app_3)
        self.spinBox_app.setObjectName("spinBox_app")
        self.gridLayout_10.addWidget(self.spinBox_app, 1, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.groupBox_app_3)
        self.label_30.setEnabled(True)
        self.label_30.setObjectName("label_30")
        self.gridLayout_10.addWidget(self.label_30, 2, 0, 1, 1)
        self.lineEdit_app_4 = QtWidgets.QLineEdit(self.groupBox_app_3)
        self.lineEdit_app_4.setEnabled(True)
        self.lineEdit_app_4.setText("")
        self.lineEdit_app_4.setObjectName("lineEdit_app_4")
        self.gridLayout_10.addWidget(self.lineEdit_app_4, 2, 1, 1, 1)
        self.verticalLayout_18.addLayout(self.gridLayout_10)
        self.verticalLayout_11.addWidget(self.groupBox_app_3)
        self.pushButton_app_2 = QtWidgets.QPushButton(self.desktopAppWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_app_2.sizePolicy().hasHeightForWidth())
        self.pushButton_app_2.setSizePolicy(sizePolicy)
        self.pushButton_app_2.setObjectName("pushButton_app_2")
        self.verticalLayout_11.addWidget(self.pushButton_app_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem9)
        self.tabStackWidget.addWidget(self.desktopAppWidget)
        self.verticalLayout_3.addWidget(self.splitter)
        self.buttonBox = QtWidgets.QDialogButtonBox(Opciones)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Apply|QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok|QtWidgets.QDialogButtonBox.Reset)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(Opciones)
        self.tabStackWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(Opciones)

    def retranslateUi(self, Opciones):
        _translate = QtCore.QCoreApplication.translate
        Opciones.setWindowTitle(_translate("Opciones", "Opciones"))
        __sortingEnabled = self.listWidgetDevices.isSortingEnabled()
        self.listWidgetDevices.setSortingEnabled(False)
        item = self.listWidgetDevices.item(0)
        item.setText(_translate("Opciones", "Servidor Central"))
        item = self.listWidgetDevices.item(1)
        item.setText(_translate("Opciones", "Grabador"))
        item = self.listWidgetDevices.item(2)
        item.setText(_translate("Opciones", "Detector"))
        item = self.listWidgetDevices.item(3)
        item.setText(_translate("Opciones", "App"))
        self.listWidgetDevices.setSortingEnabled(__sortingEnabled)
        self.groupBox_server_1.setTitle(_translate("Opciones", "Añadir puesto"))
        self.label_8.setText(_translate("Opciones", "Nombre puesto:"))
        self.label_34.setText(_translate("Opciones", "Coordenadas puesto:"))
        self.groupBox.setTitle(_translate("Opciones", "Grabador"))
        self.label_5.setText(_translate("Opciones", "Proxy:"))
        self.label_4.setText(_translate("Opciones", "Puerto:"))
        self.label_3.setText(_translate("Opciones", "IP:"))
        self.groupBox_2.setTitle(_translate("Opciones", "Deco"))
        self.label_7.setText(_translate("Opciones", "IP:"))
        self.label_32.setText(_translate("Opciones", "Proxy:"))
        self.label_33.setText(_translate("Opciones", "Puerto:"))
        self.pushButton_server.setText(_translate("Opciones", "Añadir"))
        self.groupBox_server_2.setTitle(_translate("Opciones", "Editar puesto"))
        self.comboBox_server.setItemText(0, _translate("Opciones", "Seleccione puesto"))
        self.label_6.setText(_translate("Opciones", "Nombre puesto:"))
        self.label_35.setText(_translate("Opciones", "Coordenadas:"))
        self.label.setText(_translate("Opciones", "IP (grabador / deco):"))
        self.label_2.setText(_translate("Opciones", "Nombre del Proxy (grabador / deco):"))
        self.label_9.setText(_translate("Opciones", "Puerto (grabador / deco):"))
        self.pushButton_server_5.setText(_translate("Opciones", "Ver configuración"))
        self.groupBox_3.setTitle(_translate("Opciones", "Eliminar puesto"))
        self.comboBox_server_2.setItemText(0, _translate("Opciones", "Seleccione puesto"))
        self.pushButton_server_2.setText(_translate("Opciones", "Ver configuración"))
        self.pushButton_server_3.setText(_translate("Opciones", "Eliminar (falta implementar en CS)"))
        self.pushButton_server_4.setText(_translate("Opciones", "Ver Configuración General"))
        self.groupBox_grabador_1.setTitle(_translate("Opciones", "Editar puesto"))
        self.comboBox_grabador.setItemText(0, _translate("Opciones", "Seleccionar puesto"))
        self.groupBox_grabador_2.setTitle(_translate("Opciones", "Parámetros básicos"))
        self.label_13.setText(_translate("Opciones", "Cambiar tamaño disco [GB]: "))
        self.label_10.setText(_translate("Opciones", "Nombre: "))
        self.label_11.setText(_translate("Opciones", "Carpeta grabaciones:"))
        self.label_12.setText(_translate("Opciones", "Nombre del Proxy:"))
        self.lineEdit_grabador_2.setText(_translate("Opciones", "Por implementar"))
        self.groupBox_grabador_3.setTitle(_translate("Opciones", "Piloto de activación"))
        self.label_31.setText(_translate("Opciones", "Ubicación piloto:"))
        self.label_14.setText(_translate("Opciones", "Número activación: "))
        self.label_15.setText(_translate("Opciones", "Número desactivación: "))
        self.groupBox_grabador_4.setTitle(_translate("Opciones", "Dispositivos conectados (Cámaras)"))
        self.label_16.setText(_translate("Opciones", "Añadir Cámara (IP): "))
        self.label_17.setText(_translate("Opciones", "Eliminar Cámara (IP): "))
        self.pushButton_grabador.setText(_translate("Opciones", "Ver Configuración"))
        self.pushButton_grabador_2.setText(_translate("Opciones", "Restaurar valores por defecto"))
        self.groupBox_deco_1.setTitle(_translate("Opciones", "Editar puesto"))
        self.comboBox_deco.setItemText(0, _translate("Opciones", "Seleccionar puesto"))
        self.groupBox_deco_2.setTitle(_translate("Opciones", "Zona de detección"))
        self.label_21.setText(_translate("Opciones", "Ubicación fichero zona: "))
        self.lineEdit_deco_1.setText(_translate("Opciones", "Por implementar"))
        self.label_19.setText(_translate("Opciones", "Editar zona:"))
        self.groupBox_deco_3.setTitle(_translate("Opciones", "Porcentaje de detección"))
        self.label_22.setText(_translate("Opciones", "Ubicación fichero porcentaje: "))
        self.lineEdit_deco_3.setText(_translate("Opciones", "Por implementar"))
        self.label_20.setText(_translate("Opciones", "Editar porcentaje [%]: "))
        self.groupBox_deco_4.setTitle(_translate("Opciones", "Configuración primer fondo"))
        self.pushButton_deco_2.setText(_translate("Opciones", "Obtener"))
        self.pushButton_deco_1.setText(_translate("Opciones", "Ver Configuración"))
        self.pushButton_deco_3.setText(_translate("Opciones", "Restaurar valores por defecto"))
        self.groupBox_app_1.setTitle(_translate("Opciones", "Parámetros básicos"))
        self.label_23.setText(_translate("Opciones", "Ubicación de descargas: "))
        self.groupBox_app_2.setTitle(_translate("Opciones", "Administración de permisos"))
        self.comboBox_app.setItemText(0, _translate("Opciones", "Seleccionar usuario"))
        self.label_24.setText(_translate("Opciones", "Manipular dispositivo/deco: "))
        self.label_25.setText(_translate("Opciones", "Manipular Central Server: "))
        self.label_27.setText(_translate("Opciones", "Generación de  reporte: "))
        self.label_26.setText(_translate("Opciones", "Modo offline / conexión directa: "))
        self.groupBox_app_3.setTitle(_translate("Opciones", "Configuración con Central Server"))
        self.label_28.setText(_translate("Opciones", "IP: "))
        self.label_29.setText(_translate("Opciones", "Puerto:"))
        self.label_30.setText(_translate("Opciones", "Proxy: "))
        self.pushButton_app_2.setText(_translate("Opciones", "Ver Configuración"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Opciones = QtWidgets.QDialog()
    ui = Ui_Opciones()
    ui.setupUi(Opciones)
    Opciones.show()
    sys.exit(app.exec_())

